### ISSUE TITLE
Is it possible to deploy stack to accounts without stack_set?

### ISSUE THREAD

**Issue by akefirad** [aws-solutions/aws-control-tower-customizations#100]
**Is your feature request related to a problem? Please describe.**
To prevent XY problem, here's my use case. I'm trying to manage CDK bootstrap stacks for all accounts in CfCT. But the problem is that CDK needs to know the bootstrap stack name. There are ways to give the name while running the command, but I think it gets too complicated when it comes to cross-account deployment.
Now, the current implementation of CfCT uses stack-sets to deploy stacks to accounts (correct me if I'm wrong). And AFAIK, this way, it's not possible to set a proper name for stack instances.

**Describe the feature you'd like**
To be able to deploy stacks to accounts with a custom name.

Thanks.

**Comment by balltrev** [comment]
Hey @akefirad, Customizations for Control Tower has a hard dependency on StackSets, and the CloudFormation Stacks deployed follow a naming scheme of "StackSet-CustomControlTower-$STACKNAME-$GUID" where $STACKNAME is defined by the value to the `name` key in the manfiest for a resource. Are you looking for further customization here?

**Comment by akefirad** [comment]
Well the requirement on CDK side is to name the bootstrap stack exactly `CDKToolkit`, otherwise you have to always give the stack name every time you run a CDK command. There might be a way to set this globally but the GUID thingy makes it impossible. So ideally I want to name the stack exactly `CDKToolkit`, if not possible, drop the GUID. If not possible then I guess it's not possible to manage CDK bootstrap stack using CfCT. Any thought? Thanks.

**Comment by balltrev** [comment]
Since CfCT relies on StackSets to deploy, dropping GUIDs is not possible with the current implementation.  
 
CDK manages the lifecycle of it's bootstrap stacks as updates are published, currently it is not recommend to use CfCT to manage the CDK bootstrap stacks as it doesn't account for the updates of these stacks. I would recommend opening a feature request with [AWS CDK](https://github.com/aws/aws-cdk)

**Comment by akefirad** [comment]
Interestingly I tried this setup (CDK bootstrap stack managed by CfCT) and managed to deploy the application stack (via CDK cross account pipeline). I just needed to set `tookitStackName` (of the CDK stack in the CICD account) in `cdk.json` of the project. It seems the pipeline doesn't need to know anything about the CDK stack in the workload account.
I'll reach out to CDK team and see what's their recommendation. Thanks.

**Comment by balltrev** [comment]
Just to clarify, CfCT doesn't explicitly prevent management of the CDK Bootstrap stacks, and as you noted it should work. The issue becomes management of the lifecycle of those stacks. Going to go ahead and close this issue for now, thanks @akefirad!
