### ISSUE TITLE
Cannot deploy template with Transforms (requires capabilities: [CAPABILITY_AUTO_EXPAND]

### ISSUE THREAD

**Issue by sboonyakiatACR** [aws-solutions/aws-control-tower-customizations#105]
**Describe the bug**
When using ControlTower to deploy any template that has a serverless application (which requires Transform) The pipeline failed at Step Function phrase

**To Reproduce**
Deploy any CF template containing "Type: AWS::Serverless::Application" resource type that requires you to declare  "Transform: 'AWS::Serverless-2016-10-31' on the CF template" from ControlTower

**Expected behavior**
The Serverless Application should have gotten deployed

**Please complete the following information about the solution:**
- [ ] Version: 2.0.0

- [ ] Region: us-east-1
- [ ] Was the solution modified from the version published on this repository?:  We are still using version 2.0.0
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?: Yes your 2.0.0 version
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?: Not relate to Quota
- [ ] Were there any errors in the CloudWatch Logs?: Error in Stepfunction

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

![image](https://user-images.githubusercontent.com/68394870/164492998-3bbaeb9b-1fd1-45f7-9e80-1bc0d06b32ae.png)

![image](https://user-images.githubusercontent.com/68394870/164493474-573a3d60-e242-4f75-b55f-77c36eee7f13.png)

**Additional context**

**Comment by snebhu3** [comment]
@sboonyakiatACR the support for capability was added in [v2.2.0](https://github.com/aws-solutions/aws-control-tower-customizations/releases/tag/v2.2.0). Could you use [CFCT's latest version v2.3.0](https://github.com/aws-solutions/aws-control-tower-customizations/releases/tag/v2.3.0) and retry your customization request?
