### ISSUE TITLE
Deployment fails if CfCT and CT are not in the same region

### ISSUE THREAD

**Issue by Nr18** [aws-solutions/aws-control-tower-customizations#106]
**Describe the bug**

In my `manifest.yml` I have the following:

```yaml
---
region: eu-west-1  # Control Tower Home Region
version: 2021-03-15
```

But CfCT is enrolled in the `us-east-1` region, when running the pipeline it fails on the `CloudformationResource` with the following error:

> Unhandled Exception: An error occurred (StackSetNotFoundException) when calling the ListStackInstances operation: StackSet AWSControlTowerBP-BASELINE-CONFIG not found

The reason why it fails is that the CloudformationResource project expects a AWSControlTowerBP-BASELINE-CONFIG stack. I checked my CT home region is `eu-west-1` this has the AWSControlTowerBP-BASELINE-CONFIG stack. But the customization is deployed in `us-east-1`.

**To Reproduce**
Deploy CfCT in `us-east-1` and CT in `eu-west-1` run the pipeline.

**Expected behavior**
I would expect the pipeline to succeed. The boto client should use the configured region when querying for resources in the account.

**Please complete the following information about the solution:**
- [x] Version: 2.3.0
- [x] Region: us-east-1 (CfCT) eu-west-1 (CT)
- [x] Was the solution modified from the version published on this repository? No
- [x] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? No, but the error does not lead to a quota error
- [x] Were there any errors in the CloudWatch Logs? Yes

**Screenshots**
N/A

**Additional context**
N/A

**Comment by snebhu3** [comment]
@Nr18 thank you for reaching out. This is an expected behavior. 
CFCT is required to be deployed in the same account and region as the Control Tower landing zone deployment. Please refer to [CFCT deployment considerations documentation](https://docs.aws.amazon.com/controltower/latest/userguide/cfct-considerations.html).

**Comment by Nr18** [comment]
Redeployed the solution in the same region. Obviously that worked as it's expected behaviour I will close the issue.
