### ISSUE TITLE
AWSControlTowerExecution role is needed in management account to deploy StackSet

### ISSUE THREAD

**Issue by jo-koe** [aws-solutions/aws-control-tower-customizations#109]
**Describe the bug**
As mentioned in the [docs](https://docs.aws.amazon.com/controltower/latest/userguide/cfct-root-ou.html) we can now deploy StackSets also to the management account. But this doesn't work as the management account doesn't have the `AWSControlTowerExecution` role. Error message in Cloudformation:

```
Account *** should have 'AWSControlTowerExecution' role with trust relationship to Role 'service-role/AWSControlTowerStackSetRole'.
```

**To Reproduce**
Deploy a StackSet to the Management account.

**Expected behavior**
Deployment works.

**Please complete the following information about the solution:**
- [x] Version: v2.3.0
- [x] Region: _all_
- [x] Was the solution modified from the version published on this repository? _No_
- [x] If the answer to the previous question was yes, are the changes available on GitHub? _No_
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? _Yes_
- [x] Were there any errors in the CloudWatch Logs? _See above_

**Screenshots**
N/A

**Additional context**
N/A

**Comment by balltrev** [comment]
Hey @jo-koe, this is actually the intended behavior, in the documentation we call out why this is.

>As per AWS Control Tower best practices, the management account is intended only to manage member accounts and for billing purposes. Do not run production workloads in the AWS Control Tower management account.
>
>In accordance with best practices guidance, AWS Control Tower deployment puts the management account under the Root OU, so that it has full access and does not run additional resources. For this reason, the AWSControlTowerExecutionRole role is not deployed to the management account.
>
>We recommend that you follow these best practices for the management account. If you have a specific use case that requires you to deploy stacksets in the management account, include accounts as a deployment target and specify the management account. Otherwise, do not include accounts as a deployment target. You must create the missing resources, including required IAM roles, in the management account.

**Comment by jo-koe** [comment]
Okay thanks for the clarification.
