### ISSUE TITLE
v2.3.0 should be deployed to official S3 repository

### ISSUE THREAD

**Issue by mdaehnert** [aws-solutions/aws-control-tower-customizations#110]
**Issue:**
Currently the v2.3.0 states [on its release notes](https://github.com/aws-solutions/aws-control-tower-customizations/releases/tag/v2.3.0), that 
_Customers should now download the Customizations for AWS Control Tower CloudFormation Template from GitHub instead of S3_

As [CfCT lab](https://controltower.aws-management.tools/automation/cfct/) leverages the official S3 template, others will fail to use the right one.

**Request:**
Push v2.3.0 template file to https://s3.amazonaws.com/solutions-reference/customizations-for-aws-control-tower/latest/custom-control-tower-initiation.template

**Comment by balltrev** [comment]
Hey @mdaehnert, per the release notes, GitHub is now the official source of distribution for CfCT as of v2.3.0. 

We will work with the owners of CfCT lab to update documentation to reflect this.

**Comment by jrosco** [comment]
Sorry to highjack this issue, but what about the deploy zip files in the s3 solutions bucket? 

For example the following S3 file does not exist for v2.3.0
```
s3://solutions-reference/customizations-for-aws-control-tower/v2.3.0/custom-control-tower-state-machine.zip
```

but v2.2.0 does exist
```
s3://solutions-reference/customizations-for-aws-control-tower/v2.2.0/custom-control-tower-state-machine.zip
```

Will v2.3.0 be added to the `solutions-reference` bucket?

**Comment by balltrev** [comment]
@jrosco the bucket location was updated as part of the v2.3.0 release, which was automatically included in the new source for the [CfCT template](https://github.com/aws-solutions/aws-control-tower-customizations/blob/main/customizations-for-aws-control-tower.template)

For non-self deployed/hosted CfCT deployments, the files are all sourced from this new bucket, as an example for the state machine zip:
```
s3://control-tower-cfct-assets-prod/customizations-for-aws-control-tower/v2.3.0/custom-control-tower-state-machine.zip
```
