### ISSUE TITLE
CodeCommitBranchName doesn't affect initially created branch for CodeCommit during installation

### ISSUE THREAD

**Issue by mdaehnert** [aws-solutions/aws-control-tower-customizations#117]
**Describe the bug**
Parameter _CodeCommitBranchName_ can be set to change CodePipeline's CodeCommit branch to use. Unfortunately the CodeCommit repository itself will always set up its manifest etc. files on _main_ branch.

**To Reproduce**
Install CfCT and change the _CodeCommitBranchName_ parameter.

**Expected behavior**
If changing the branch name for the Pipeline it should reflect installing the initial repository data into the same branch. Or at least the parameter should be renamed to tell that it only affects the CodePipeline's used branch name not the initially created on by CodeCommit.

**Please complete the following information about the solution:**
- 2.3.0

**Additional context**
CloudFormation documentation for AWS::CodeCommit::Repository --> Code --> BranchName setting: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codecommit-repository-code.html#cfn-codecommit-repository-code-branchname

**Comment by balltrev** [comment]
Thanks for bringing this up, @mdaehnert. I've made a backlog for your suggestion with the team.

**Comment by stumins** [comment]
Hi @mdaehnert 

CFCT [v2.7.0](https://github.com/aws-solutions/aws-control-tower-customizations/releases/tag/v2.7.0) now honors this parameter during repo creation - the example code is now committed to your chosen branch instead of `main`.
