### ISSUE TITLE
[Bug] Templates containing non-US-ASCII characters fail to deploy in v2.3.1

### ISSUE THREAD

**Issue by stumins** [aws-solutions/aws-control-tower-customizations#121]
**Describe the bug**
Templates containing non-US-ASCII characters (e.g. ©) cause the CFCT pipeline to fail at the Build stage due to fatal cfn-nag errors:

```
| FAIL FATAL|

| #<ArgumentError: invalid byte sequence in US-ASCII>
Failures count: 1
Warnings count: 0
```

**WORKAROUNDS**: 
- Remove the special characters from your template. 
- If this is not possible, update the buildspec for the Build stage of the CFCT pipeline and add the following flag to the `dpkg-reconfigure` 

```
dpkg-reconfigure --frontend noninteractive
```
- Downgrade to CFCT v2.3.0

**To Reproduce**
- Commit a template with a non-US-ASCII character to your CFCT source repo/bucket

**Expected behavior**
- CFCT to handle all characters that are considered valid CloudFormation

**Please complete the following information about the solution:**
- This bug was introduced in CFCT v2.3.1
- This bug impacts deployments in all regions

**Comment by balltrev** [comment]
Release [v2.4.0](https://github.com/aws-solutions/aws-control-tower-customizations/releases/tag/v2.4.0) addresses this regression.
