### ISSUE TITLE
do we need to upload the distrubutables to s3 buckets manually? Also, I saw two S3 bucket one is for global one is for regional, do I need to create both of them?

### ISSUE THREAD

**Issue by condescendent** [aws-solutions/aws-control-tower-customizations#123]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Please complete the following information about the solution:**
- [ ] Version: [e.g. v1.0.0]

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0089) - customizations-for-aws-control-tower Solution. Version: v1.0.0_". You can also find the version from [releases](https://github.com/aws-solutions/aws-control-tower-customizations/releases)

- [ ] Region: [e.g. us-east-1]
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by balltrev** [comment]
Hey @condescendent, thanks for the questions:

> do we need to upload the distrubutables to s3 buckets manually?

Yes, if you're deploying your own hosted version of CfCT, you'll need to upload your own distributables to the buckets you choose

> Also, I saw two S3 bucket one is for global one is for regional, do I need to create both of them?

CfCT Does make some assumptions that resources live in regionalized buckets, so those will need to be created as well.
