### ISSUE TITLE
Recursive OU deployment targets

### ISSUE THREAD

**Issue by afroman-lw** [aws-solutions/aws-control-tower-customizations#141]
It's annoying when you have to specify the nested OUs several layers deep when you want to apply the resource to all accounts in a parent OU.

Rather than specifying each specific OU path:
```yaml
organizational_units:
  - OuName1:OUName2:OUName3
  - OuName1:OUName2:OUName4
  - OuName1:OUName5:OUName6
```

You should only need to specify a top level OU and it gets applied to all lower accounts. Like how SCPs work:
```yaml
organizational_units:  
  - OuName1
```

**Comment by hanafya** [comment]
Hello! We currently have a backlog for this feature! Duplicate issue https://github.com/aws-solutions/aws-control-tower-customizations/issues/131
