### ISSUE TITLE
Deprecation warning for aws/codebuild/standard:5.0

### ISSUE THREAD

**Issue by RutgerBeyen** [aws-solutions/aws-control-tower-customizations#152]
Deprecation warning for Codebuild images:
- Ubuntu standard 5.0 Docker Image
- Amazon Linux 2 ARM standard 1.0
- Amazon Linux 2 standard 3.0

Image aws/codebuild/standard:5.0 is being used in recources "CustomControlTowerCodeBuild", "SCPCodeBuild" and "StackSetCodeBuild"

Deprecation going into effect on March 30, 2023.

> Starting March 30, 2023, AWS CodeBuild will be moving these images to an unsupported status and they will not be cached on the build hosts anymore.

You may continue using these images for your builds, but you will notice an increase in provisioning latency after March 30, 2023.
These images will also not be getting any new updates. We recommend updating your Build Projects to use the latest build images in order to get the latest language runtimes and tools

**Comment by bshaw** [comment]
It seems they've cancelled this deprecation. I received a mail on 17th March stating

> AWS CodeBuild notified customers on March 2, 2023 that the Ubuntu 20.04 standard 5.0 image [1] will be deprecated on March 30, 2023. We have since revised the decision and will not be deprecating this image. You may continue using the image as it will continue to get future updates.

There's an open PR to bump to image version 6.0, so seems like this will be resolved regardless - #151

**Comment by stumins** [comment]
Hi @RutgerBeyen,

As mentioned the AWS CodeBuild team has decided to indefinitely postpone the deprecation of the `standard:5.0` CodeBuild image. We'll continue to monitor the deprecation timeline & make needed updates if that changes.
