### ISSUE TITLE
PIP error in Project Build

### ISSUE THREAD

**Issue by luccabastos** [aws-solutions/aws-control-tower-customizations#154]
I was working normally, when I pushed and started the build a script crash started:

ERROR: pip dependency resolver does not currently take into account all the packages that are installed. This behavior is the source of the following dependency conflicts.
cfn-lint 0.72.2 requires pyyaml>5.4, but has pyaml 5.3.1 which is incompatible.
aws-sam-cli 1.72.0 requires pyYAML==5.*,>=5.4.1, but has pyyaml 5.3.1, which is incompatible.

**Comment by stumins** [comment]
Hi @luccajbastos,

Thanks for reporting this issue. We were able to reproduce this message in our test accounts, but the error does not appear to prevent CFCT from operating correctly. Are you experiencing any issues other than seeing this error message in the logs?

We've taken a backlog item to investigate resolving this error.

**Comment by mbevc1** [comment]
Related to #169

**Comment by JamesActually** [comment]
With the [v2.7.3](https://github.com/aws-solutions/aws-control-tower-customizations/releases/tag/v2.7.3) release, we moved to PyYAML 5.4.1 which should resolve this error.
