### ISSUE TITLE
CFT Download to verify with deployed CFT fails because of wrong S3 path

### ISSUE THREAD

**Issue by rcalvachi** [aws-solutions/aws-control-tower-customizations#155]
Deploying a CFn template from a URL in the manifest succeeds. However, the next time CfCT runs, it tries to download the CFT from the URL to compare with the deployed CFT. It fails because the path is wrong, it has an extra **amazonaws**. 

`https://s3.amazonaws.amazonaws.com/<path>/<template>.yaml`

It should be:

`https://s3.amazonaws.com/<path>/<template>.yaml`  

**NOTE:**  Using CfCT v2.5.2

![image](https://user-images.githubusercontent.com/1895777/233194809-422750d3-0e0d-4379-aa0c-0ef42d0801ff.png)

The details in the **manifest.yaml**

```
  - name: CID-CUR-Destination
    resource_file: https://aws-managed-cost-intelligence-dashboards.s3.amazonaws.com/cfn/cur-aggregation.yaml
    deploy_method: stack_set
```

**Comment by snebhu3** [comment]
@rcalvachi Thank you for reaching out.
The expected format of resource_file in this case is `https://bucket-name.s3.Region.amazonaws.com/key-name`
The resource_file url provided in the manifest.yaml is missing a `Region` potentially causing this error.

Please may you re-try with the updated URL format?

**Comment by rcalvachi** [comment]
Thank you. As you suggested, using the URL with a region worked. :-)

**Comment by balltrev** [comment]
Glad to hear it @rcalvachi!
