### ISSUE TITLE
BUILDS FAILING

### ISSUE THREAD

**Issue by mightymouse2045** [aws-solutions/aws-control-tower-customizations#160]
**Describe the bug**
Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: apt-get -q update 1> /dev/null && apt-get -q upgrade -y 1> /dev/null. Reason: exit status 100

**To Reproduce**
Deploy update to CFCT

**Expected behavior**
pipline should run

- [X] Region: ap-southeast-2
![image](https://github.com/aws-solutions/aws-control-tower-customizations/assets/878160/6c6099b3-a5f6-48f0-87bd-e53b25a91686)

**Comment by hanafya** [comment]
Hey @mightymouse2045 we're unable to reproduce this failure in our test and prod environment. I would recommend you work with AWS Premium Support to further deep dive this failure in your environment.
