### ISSUE TITLE
custom-control-tower-scripts.zip no longer publicly accessible

### ISSUE THREAD

**Issue by DaniDipp** [aws-solutions/aws-control-tower-customizations#161]
**Describe the bug**
Trying to download `s3://control-tower-cfct-assets-prod/customizations-for-aws-control-tower/v2.5.3/custom-control-tower-scripts.zip` now runs into 403 errors, breaking the CodePipeline tasks

**To Reproduce**
```
aws s3 cp s3://control-tower-cfct-assets-prod/customizations-for-aws-control-tower/v2.5.3/custom-control-tower-scripts.zip .
```

**Expected behavior**
The scripts should be able to be downloaded.

**Please complete the following information about the solution:**
- [x] Version: v2.5.2 and v2.5.3 (I tried updating to fix the breaking build)

- [x] Region: eu-central-1
- [x] Was the solution modified from the version published on this repository? No
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices[sic] this solution uses? No
- [x] Were there any errors in the CloudWatch Logs? See screenshot

**Screenshots**
![2023-05-16T23-51-36](https://github.com/aws-solutions/aws-control-tower-customizations/assets/17002453/bb241381-7d25-40fd-9e57-07035fc7a704)

**Additional context**
It still worked 2 hours ago (I was still on 2.5.2 then)

**Comment by hanafya** [comment]
Hi @DaniDipp , thank for you alerting us to this issue. We've investigated the root cause and applied a fix. Can you retry and confirm that the issue is resolved?

**Comment by DaniDipp** [comment]
I can confirm that the issue is resolved, and the pipelines are running again 👍 
Thank you for the fast response!
