### ISSUE TITLE
CfCT Deployment Failed in bahrain

### ISSUE THREAD

**Issue by josukuttyulahannan** [aws-solutions/aws-control-tower-customizations#163]
**Describe the bug**
CloudFormation Stack Failed When deployed in bahrain region(me-south-1)

While deploying cfct in my landing zone in bahrain region, its giving me this error:

Resource handler returned message: "Your access has been denied by S3, please make sure your request credentials have permission to GetObject for control-tower-cfct-assets-prod-me-south-1/customizations-for-aws-control-tower/v2.5.3/custom-control-tower-state-machine.zip. S3 Error Code: AccessDenied. S3 Error Message: Access Denied (Service: Lambda, Status Code: 403, Request ID: b48a7d09-e4c8-432e-956f-0ec1a42d14c5)" (RequestToken: 0b2cb020-5cf2-8b17-b4c3-06499dbccb84, HandlerErrorCode: AccessDenied)

At the same time it is working fine for other regions, ap-south-1, eu-west-1

**To Reproduce**
Upload the template in bahrain

**Expected behavior**
CfCT stack successfully deployed

**Please complete the following information about the solution:**
- [ ] Version: v2.5.3

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0089) - customizations-for-aws-control-tower Solution. Version: v1.0.0_". You can also find the version from [releases](https://github.com/aws-solutions/aws-control-tower-customizations/releases)

- [ ] Region: [ me-south-1]
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? yes
- [ ] Were there any errors in the CloudWatch Logs? 

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by hanafya** [comment]
Hey @josukuttyulahannan! Thank you for bringing this to our attention! me-south-1 is only supported in v2.6.0 of CFCT. You will need to upgrade to v2.6.0. Please see, https://github.com/aws-solutions/aws-control-tower-customizations/releases/tag/v2.6.0

**Comment by josukuttyulahannan** [comment]
> Hey @josukuttyulahannan! Thank you for bringing this to our attention! me-south-1 is only supported in v2.6.0 of CFCT. You will need to upgrade to v2.6.0. Please see, https://github.com/aws-solutions/aws-control-tower-customizations/releases/tag/v2.6.0

@hanafya Thank you for the quick response. CfCT is working fine in Bahrain now !
