### ISSUE TITLE
It is desirable that not only createManagedAccount, but also the CFCT pipeline starts even when a moveAccount action occurs

### ISSUE THREAD

**Issue by sudakos** [aws-solutions/aws-control-tower-customizations#173]
If the OU is moved due to re-registration of the AWS account, the managed functionality of Control Tower will be updated, but the CFCT template will not be re-applied.
I want you to make sure that there is no inconsistency between services in behavior with respect to manual workloads when linking services.
So, If an AWS account has moved an OU, I think it is a desirable specification that both Control Tower controls and CFCT templates are applied with the policies applied to the relevant OU.

**Comment by stumins** [comment]
Hi @sudakos,

Thanks for submitting this feature request. I've created a backlog item to update the LifecyleEvent EventBridge rule to trigger the CFCT customization pipeline when the Landing Zone emits `UpdateManagedAccount` events in addition to `CreateManagedAccount` events.

**Comment by stumins** [comment]
Hi @sudakos,

We just released CFCT [v2.7.0](https://github.com/aws-solutions/aws-control-tower-customizations/releases/tag/v2.7.0) which adds this behavior - the CFCT pipeline is now also triggered by `UpdateManagedAccount` events.
