### ISSUE TITLE
Support for Israel(Tel Aviv) Region "il-central-1"

### ISSUE THREAD

**Issue by veltz-avi** [aws-solutions/aws-control-tower-customizations#179]
The solution deployment is failing in Israel(Tel Aviv) Region "il-central-1"
Version: v2.7.0

**Additional context**
Resource handler returned message: "Your access has been denied by S3, please make sure your request credentials have permission to GetObject for control-tower-cfct-assets-prod-il-central-1/customizations-for-aws-control-tower/v2.7.0/custom-control-tower-state-machine.zip. S3 Error Code: AccessDenied. S3 Error Message: Access Denied (Service: Lambda, Status Code: 403, Request ID: 6097d934-f2ca-4141-bcdb-56777103a12a)" (RequestToken: 50ea6444-36d1-f368-a73c-026d03f58809, HandlerErrorCode: AccessDenied)

![Screenshot 2023-12-24 at 16 53 02](https://github.com/aws-solutions/aws-control-tower-customizations/assets/68636084/c0ee313f-fefe-4f61-9204-966dcea11a06)

**Comment by stumins** [comment]
Hi @veltz-avi,

As indicated in the [Control Tower limitations page](https://docs.aws.amazon.com/controltower/latest/userguide/limits.html#controltower-limits), CFCT is currently not supported in the Tel Aviv `il-central-1` region.

I've added this request to the backlog item for supporting CFCT in `il-central-1`.

**Comment by JamesActually** [comment]
With release [v2.7.2](https://github.com/aws-solutions/aws-control-tower-customizations/releases/tag/v2.7.2), CfCT is supported in the Tel Aviv `il-central-1` region.
