### ISSUE TITLE
Update CHANGELOG

### ISSUE THREAD

**Issue by swathi-c** [aws-solutions/aws-control-tower-customizations#182]
**Describe the bug**
CHANGELOG.md does not include changes being made for release. Last update was for 2.4.0

**To Reproduce**
Check CHANGELOG.md.

**Expected behavior**
Change log should include bugs/features worked on for that specific release.

**Please complete the following information about the solution:**
- Please include changes made for all versions released after 2.4.0

**Comment by laminarcode** [comment]
[CHANGELOG.md](https://github.com/aws-solutions/aws-control-tower-customizations/blob/main/CHANGELOG.md) shows latest release as [2.4.0](https://github.com/aws-solutions/aws-control-tower-customizations/blob/main/CHANGELOG.md#240---2022-06-08)

https://github.com/aws-solutions/aws-control-tower-customizations/releases shows current release being v2.7.0

Please reconcile!

**Comment by JamesActually** [comment]
We updated our process to ensure CHANGELOG.md is updated with each release.  All releases up to the latest have been backfilled to the file.

Thanks for reporting this!
