### ISSUE TITLE
Nested Organizational Units may not be specified.

### ISSUE THREAD

**Issue by bcw1000** [aws-solutions/aws-control-tower-customizations#19]
AWS supports Organizational Units to a depth of 5.  Organizational Units may be specified as the target for deployment of SCPs, but only at the level directly beneath the root of an Organization.

A delimiter character is mentioned in one test file, but the feature is not implemented.

**Comment by bcw1000** [comment]
#20 PR written to implement feature.

**Comment by groverlalit** [comment]
Thanks for reaching out to us. We have added this to our backlog.

**Comment by lennartt** [comment]
Is there any estimate on when this feature would be implemented?

**Comment by trevorlatson** [comment]
Because Control Tower does not support nested OU's, adding this feature could cause some confusion.

**Comment by rjenks** [comment]
Now that Control Tower officially supports nested OUs, how long until this framework supports it?

https://aws.amazon.com/about-aws/whats-new/2021/11/aws-control-tower-supports-nested-organizational-units/

**Comment by peterchova** [comment]
> Now that Control Tower officially supports nested OUs, how long until this framework supports it?
> 
> https://aws.amazon.com/about-aws/whats-new/2021/11/aws-control-tower-supports-nested-organizational-units/

yeah, many are eager to deploy nested OU in Control Tower but cannot proceed until this feature is added in the solution.

**Comment by aijunpeng** [comment]
This feature has been released.
