### ISSUE TITLE
Python 3.8 End-Of-Life

### ISSUE THREAD

**Issue by lazize** [aws-solutions/aws-control-tower-customizations#193]
**Is your feature request related to a problem? Please describe.**
We are ending support for Python 3.8 in Lambda on October 14, 2024. This follows Python 3.8 End-Of-Life (EOL) which is scheduled for October, 2024 [1].

As described in the Lambda runtime support policy [2], end of support for language runtimes in Lambda happens in several stages. Starting on October 14, 2024, Lambda will no longer apply security patches and other updates to the Python 3.8 runtime used by Lambda functions, and functions using Python 3.8 will no longer be eligible for technical support. Also, Python 3.8 will no longer be available in the AWS Console, although you can still create and update functions that use Python 3.8 via AWS CloudFormation, the AWS CLI, AWS SAM, or other tools. Starting February 28, 2025, you will no longer be able to create new Lambda functions using the Python 3.8 runtime. Starting March 31, 2025, you will no longer be able to update existing functions using the Python 3.8 runtime.

We recommend that you upgrade your existing Python 3.8 functions to the latest available Python runtime in Lambda before October 14, 2024.

**Describe the feature you'd like**
Upgrade Lambda functions to latest Python version.

**Additional context**
See below all Lambda functions created by CfCT.

```shell
$ aws lambda list-functions --region sa-east-1 --output text --query "Functions[?Runtime=='python3.8'].[Funct
ionArn]" | sort
arn:aws:lambda:sa-east-1:xxxx20:function:CustomControlTowerDeploymentLambda
arn:aws:lambda:sa-east-1:xxxx20:function:CustomControlTowerStateMachineLambda
arn:aws:lambda:sa-east-1:xxxx20:function:cfct-CustomControlTowerLELambda-3Cq8lrhazVTx
```

CfCT version: (SO0089) - customizations-for-aws-control-tower Solution. Version: v2.7.0

**Comment by minosmlee** [comment]
Hello~
Is this issue in progress?
Many customers are asking when it will be updated.

**Comment by lazize** [comment]
Was it updated to use Python 3.11?
If so, why? Why not use the latest current version that is 3.12?

**Comment by VirginiaGraciano** [comment]
Does this mean that customer must do the update itself? or will AWS send an update time as with previous versions like 3.6?
