### ISSUE TITLE
Add support for GitHub as Source provider

### ISSUE THREAD

**Issue by RobReus** [aws-solutions/aws-control-tower-customizations#21]
In addition to S3, and the newly added CodeCommit source providers, I would like to see GitHub be added too for those of us using GitHub instead.

You should be able to select "GitHub" in the `CodePipelineSource` parameter, and then have a choice if you want to "Poll" or if you want a "Webhook" to be created. A parameter for the GitHub token secret should also be added.

**Comment by rakshb** [comment]
@RobReus Thanks for the request. We will add this to the backlog for a future release.

**Comment by kkvinjam** [comment]
IHAC looking for integration with GitHub Enterprise repository.

**Comment by groverlalit** [comment]
Thanks for creating the feature request. We have added this our backlog.

**Comment by DMEvanCT** [comment]
Can we move this along? Fortune 500 companies for the most part don't want to use CodeCommit. They want to use their own source control system

**Comment by vedant-singhania** [comment]
What's the status on this? 

Enterprises benefit the most from Control Tower, however, they prefer Github for repo management!

**Comment by word** [comment]
Looks like codecommmit has been recently deprecated so this is even more important now: https://repost.aws/questions/QUshILm0xbTjWJZSD8afYVgA/codecommit-cannot-create-a-repository#ANa5lXt9nwSiGyN8fGlmOA-Q
