### ISSUE TITLE
Create Task Failed: Canceled since failure tolerance has exceeded

### ISSUE THREAD

**Issue by ipsensejuan** [aws-solutions/aws-control-tower-customizations#28]
Hi @georgebearden @leavertj 

I would like to inform you that the step function failed due to AWS CloudFormation causing the error "Canceled since failure tolerance has exceeded".

`{
  "RequestType": "Create",
  "ResourceProperties": {
    "StackSetName": "CustomControlTower-ipsense-cloudzoom",
    "TemplateURL": "",
    "Capabilities": "CAPABILITY_NAMED_IAM",
    "Parameters": {},
    "AccountList": [
    ],
    "RegionList": [
      "us-east-1"
    ],
    "SSMParameters": {}
  },
  "params": {
    "ClassName": "CloudFormation",
    "FunctionName": "describe_stack_set_operation"
  },
  "LoopFlag": "not-applicable",
  "StackSetExist": "no",
  "StackSetStatus": "success",
  "CreateInstance": "yes",
  "DeleteInstance": "no",
  "ActiveAccountList": [
  ],
  "ActiveRegionList": [
    "us-east-1"
  ],
  "OperationId": "70a507fe-bcd7-47a7-ad26-0d3935f55e96",
  "RetryDeleteFlag": false,
  "OperationStatus": "FAILED",
  "us-east-1": "Cancelled since failure tolerance has exceeded"
}`

Thank you very much for the solution created

**Comment by lokhandwalayusuf** [comment]
@ipsensejuan - Can you please share the resolution step you followed to resolve this issue? I am facing exact same problem and have tried multiple things but no luck. 

Appreciate and thanks in advance
