### ISSUE TITLE
Documentation issue: Developer Guide cloudformation resource "name"

### ISSUE THREAD

**Issue by jdaves-ucar** [aws-solutions/aws-control-tower-customizations#31]
According to the 2020-07 Developers Guide pg 9 in referring to Cloudformation Resources:
name
The name that is associated with the AWS CloudFormation StackSets. The provided name is used to provide a more user-friendly name for a stack set.
Type: String Required: Yes
Valid Values: a-z, A-Z, 0-9, and an underscore (_). Any other character is automatically replaced with an underscore (_).

This should be accepting a hyphen (-) and not an underscore as hyphens are valid in stack names, and underscores are not.  Including an underscore results in the CloudformationResource build step to fail which can be tracked down in the step function:

"errorMessage": "An error occurred (ValidationError) when calling the CreateStackSet operation: 1 validation error detected: Value 'CustomControlTower-cloudformation_example_name' at 'stackSetName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]*"

**Comment by groverlalit** [comment]
@jdaves-ucar Thanks for bringing this to our attention. Can you please advise if you have defined the name of the stack set as 'cloudformation_example_name' in the manifest.yaml or with another special character?
Also, what is the current version of the solution are you using?
A quick review of the latest code shows that the solution does not update the stack set name with underscores.

**Comment by jdaves-ucar** [comment]
Running 1.2.0.  The names in the manifest that failed were defined with underscores based on the incorrect documentation as cloudformation_example_name, no substitution attempted.

**Comment by groverlalit** [comment]
@jdaves-ucar Thanks for confirming the stack set name. Apologies for the confusion. We have created a ticket to update the documentation. 
Please remove the underscore from the name of the stack set in the manifest file to resolve this issue.
Thanks.

**Comment by rakshb** [comment]
@jdaves-ucar We updated the developer guide to reflect this change.
