### ISSUE TITLE
Multiple capabilities needed

### ISSUE THREAD

**Issue by martin-lehmann-pfx** [aws-solutions/aws-control-tower-customizations#64]
Hi there,
not sure if that is more a feature request or a bug report. Please help me along.

I tried use AWS::Serverless::Function Resource in one of my custom templates and received the error message that the capability CAPABILITY_AUTO_EXPAND is not included. After some investigations I realised that the capability is hardcoded in source/state_machine_trigger.py
...
os.environ['CAPABILITIES'] = 'CAPABILITY_NAMED_IAM'
...

For testing purposes I then tried to add this to the step function input manually and rerun the function like this:
{"RequestType": "Create", ...<snip> ...
, "Capabilities": "CAPABILITY_NAMED_IAM, CAPABILITY_AUTO_EXPAND", ...<snip> ...
}

which then in turn leads to this error message from the step function
{
  "error": "ClientError",
  "cause": {
    "errorMessage": "An error occurred (ValidationError) when calling the UpdateStackSet operation: 1 validation error detected: Value '[CAPABILITY_NAMED_IAM, CAPABILITY_AUTO_EXPAND]' at 'capabilities' failed to satisfy constraint: Member must satisfy constraint: [Member must satisfy enum value set: [CAPABILITY_AUTO_EXPAND, CAPABILITY_NAMED_IAM, CAPABILITY_IAM]]",
    "errorType": "ClientError",
    "stackTrace": [
      "  File \"/var/task/state_machine_router.py\", line 200, in lambda_handler\n    return cloudformation(event, function_name)\n",
      "  File \"/var/task/state_machine_router.py\", line 45, in cloudformation\n    response = stack_set.update_stack_set()\n",
      "  File \"/var/task/state_machine_handler.py\", line 621, in update_stack_set\n    response = stack_set.update_stack_set(\n",
      "  File \"/var/task/aws/services/cloudformation.py\", line 272, in update_stack_set\n    response = self.cfn_client.update_stack_set(\n",
      "  File \"/var/runtime/botocore/client.py\", line 357, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n",
      "  File \"/var/runtime/botocore/client.py\", line 676, in _make_api_call\n    raise error_class(parsed_response, operation_name)\n"
    ]
  }
}

Do I understand correctly that the capabilities variable can only handle one single value out of three possible values?

Could you please advise me if that is something that can get changed or fixed or if there is some deeper underlying issue which would not allow this?

Thanks a lot, 
Cheers,
   Martin

**Comment by nascit** [comment]
Hi, ran into same issue here. I'd love to use SAM together with this solution.
Is there any ETA of when this will be supported?

**Comment by groverlalit** [comment]
Thanks for creating the feature request. We have added this our backlog.

**Comment by hkeeler** [comment]
Same. I'm trying to use SAM, and just hit up against this.

**Comment by aijunpeng** [comment]
This feature has been released.
