### ISSUE TITLE
Resources that start with S3 are incorrectly being parsed as empty buckets

### ISSUE THREAD

**Issue by milbrya** [aws-solutions/aws-control-tower-customizations#65]
https://github.com/awslabs/aws-control-tower-customizations/blob/8076f8feffeb0025431739df762b017a42db6470/source/manifest/manifest_parser.py#L364

I believe this should be 's3://'. 
I had created a resource that was named S3BPA and the code assumed it was a bucket (which didn't exist).

**Comment by groverlalit** [comment]
Thanks for bringing this our attention. We have added this our backlog.

**Comment by aijunpeng** [comment]
This issue has been fixed.
