### ISSUE TITLE
Doubt: How to destroy CfCT resources? 

### ISSUE THREAD

**Issue by evairmarinho** [aws-solutions/aws-control-tower-customizations#87]

**Comment by deolank** [comment]
We have added this to backlog to update the documentation.

**Comment by rakshb** [comment]
You can delete the solution's cloudformation stack to destroy most of the resources created by the solution.
Resources that require manual deletion:
- The S3 buckets and related artifacts created by the solution will be retained and needs to be manually deleted (CustomControlTowerPipelineS3Bucket, CustomControlTowerPipelineArtifactS3Bucket, CustomControlTowerS3AccessLogsBucket)
- If you created a Code Commit repo using the solution, that will be retained and needs to be manually deleted

**Comment by balltrev** [comment]
Hey @evairmarinho, let us know if you've got any further context here, closing this issue for now. Thanks!
